name: Refresh API response
on:
  schedule:
    - cron:  '00 11 * * *'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Make an API request, store the result in /js/response.json and commit
        run: |
          wget -O ./js/response.json "https://store.finalfantasyxiv.com/ffxivstore/en-gb/product/",
          pwd
          cd js
          ls
          cat response.json
          git config --global user.name "Roy van Dijk",
          git config --global user.email "roy.van.dijk@outlook.com",
          git commit -m "Response update",
          git pull,
          git push,
