name: Refresh API response
on:
  schedule:
    - cron: "00 11 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Make an API request, store the result in /js/responses and commit
        run: |
          cd js/responses
          wget -O response-eur.json "https://api.store.finalfantasyxiv.com/ffxivcatalog/api/products/?lang=en-gb&currency=EUR&limit=999"
          wget -O response-gbp.json "https://api.store.finalfantasyxiv.com/ffxivcatalog/api/products/?lang=en-gb&currency=GBP&limit=999"
          wget -O response-jpy.json "https://api.store.finalfantasyxiv.com/ffxivcatalog/api/products/?lang=en-gb&currency=JPY&limit=999"
          wget -O response-usd.json "https://api.store.finalfantasyxiv.com/ffxivcatalog/api/products/?lang=en-gb&currency=USD&limit=999"
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -am "Response update"
          git pull
          git push
